### ISSUE TITLE
개발 환경 설정 가이드 만들기

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#10]
완료조건
* 개발 환경 가이드를 만들고
* @baupa 님 PC에서 수행한 뒤
* 피드백을 받아 최종 검토한다.

**Comment by dali-kim** [comment]
@baupa https://docs.google.com/document/d/1NpM5q6btxQd83l884ty8I3tNer8LZmQo4mn8otKBIVQ/edit#heading=h.qhj65oo5jpe 이 문서로 설치 시도 한 번 해보실 수 있을까요?

**Comment by dalikim** [comment]
배포 관련된 설정은 다른 이슈에서 처리하고, 이 이슈는 종료할께요.
