### ISSUE TITLE
rails 101

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#11]
완료조건
* @baupa 님과 개발 할 수 있는 간단한 rails 101을 가진다.

**Comment by dali-kim** [comment]
@rest515 

@baupa 과 간단한 101 진행했으면 하는데요. @rest515 님이 진행해 주시면 합니다.

**Comment by dalikim** [comment]
더 진행한다는 게 의미 없어졌네요. 종료합니다.
