### ISSUE TITLE
와플을 사용해 봅니다.

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#111]

**Comment by dalikim** [comment]
@parti-xyz/core 와플에 In Progress에는 지금 하는 일을 올려 두고, Ready는 이번 주 할일을 올리면 될까나요?

**Comment by luluv** [comment]
@dalikim 그렇게 정해두면 좋을 것 같습니다!

**Comment by dalikim** [comment]
@parti-xyz/core 옴... 그럼 내일 중에 요번 주 할일을 와플에 이슈로 만들어 올려야겠군요.  https://parti-xyz.hackpad.com/d3Sy8vXjlD5#:h=주간-목표
