### ISSUE TITLE
발표 자료 docs.parti.xyz에 정리하기

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#112]

**Comment by berryv** [comment]
https://drive.google.com/drive/folders/0B1fCwOawxIhHV2hRbEpfUS1yTGs 제가 지금 모아본 것은 이 정도 입니다. 혹시 더 있는지 확인해주세요. 많았던 것 같은데 생각보다 .. 없는 것 같아서요. 그리고 혹시 서울시 발표자료는 들어가도 되는지 궁금합니다. @rest515

**Comment by rest515** [comment]
@berryv 서울시 발표는 넣지 않는게 좋겠네요.

**Comment by berryv** [comment]
@rest515 넵

**Comment by berryv** [comment]
슬라이드 쉐어도 고려 중입니다. 슬라이드 쉐어 로그인 문제로 구글 드라이브로 연결했습니다.
