### ISSUE TITLE
슬랙에서 빠띠 포럼 채널 개설에 대해 검토합니다

### ISSUE THREAD

**Issue by rest515** [parti-xyz/parti-group#114]
빠띠 주변에서 도움을 주실 만한 전문가 분들을 모실 슬랙 채널을 만들려고 합니다. 이름은 forum이 적당한 것 같구요. 
그 분들과 함께 해 볼 꺼리들도 만들어 볼 수 있을 듯 합니다.

**Comment by dalikim** [comment]
이 이슈는 어떻게 하면 완료가 되는 걸까요?

**Comment by dalikim** [comment]
팀에 제안하고 슬랙이 정리되면 완료하겠습니다. 의견있으면 주세요.
