### ISSUE TITLE
카누/카탄1.0 프로젝트 회고

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#116]

**Comment by dalikim** [comment]
https://docs.google.com/a/parti.xyz/spreadsheets/d/15oR4EC6ddIQ0dofw4FRNMOnsFxPniYVOZ7T4pb8mcq8/edit?usp=drive_web

https://docs.google.com/a/parti.xyz/spreadsheets/d/1C0h49XW4_7nSS3kBYfmkWcojbrxIhJV95uNNt2l6zik/edit?usp=drive_web

엑셀로 이력을 기록할 수 있는 문서를 열었습니다.

**Comment by dalikim** [comment]
@berry502 위에 문서는 베리님이 좀 틀을 잡아주셔야 되겠는걸요? 제 기억력이.. ㅠㅠ

**Comment by berryv** [comment]
워크샵에서 카누는 진행했습니다. 카탄은 이달 말 회고에서 함께 할까요?
