### ISSUE TITLE
docs 콜라보레이션 사례 리스트업

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#126]

**Comment by berryv** [comment]
http://docs.parti.xyz/docs/collaboration/ 

시민참여 프로젝트 : 완료 *마크다운 수정

초안 : https://docs.google.com/document/d/1du8Hs789QGfV6kyBXXF3cboLWw7yiujduWbxFckR0Ow/edit

**Comment by berryv** [comment]
깃헙에 콜라보레이션 페이지를 추가했어요. 
https://github.com/parti-xyz/parti-group 여기엔 들어가 있는데 
http://docs.parti.xyz/ 엔 반영이 안되는 문제 도움 요청합니다 .. 오늘은 바쁘시니 내일 쯤? 10일  @dalikim
