### ISSUE TITLE
1차 워크숍 계획하기

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#13]
완료조건
* 워크숍에서 논의할 꺼리들을 정리한다.
* 일정과 장소를 정한다.

**Comment by dalikim** [comment]
@rest515 

일단 시스님 드릴께요. 완료조건 등 다듬어 주세요.

**Comment by dalikim** [comment]
@rest515 
1차 워크숍 관련 문서도 만드는게 어떨까요?

**Comment by rest515** [comment]
https://goo.gl/Uuln5C 에 만들었습니다.

**Comment by dalikim** [comment]
다음 진행이 애매하네요. 칠판에 논의거리로 올렸습니다.

**Comment by dalikim** [comment]
워크샵 하시느라 수고 많으셨습니다.

관련 이슈 만들고 종료합니다.
