### ISSUE TITLE
위키 편집 연습

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#130]

**Comment by luluv** [comment]
- 위키피디아에 내 관심사 위주로 문서를 편집해본다. 
- 개별빠띠 운영가이드를 깃헙 위키로 옮겨본다.

**Comment by luluv** [comment]
https://github.com/parti-xyz/catan-web/wiki/%EB%B9%A0%EB%9D%A0-%EC%9A%B4%EC%98%81-%EA%B0%80%EC%9D%B4%EB%93%9C
