### ISSUE TITLE
조직 노선도 그리기

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#131]

**Comment by berryv** [comment]
https://github.com/parti-xyz/parti-group/blob/gh-pages/docs/collaboration.md 에 반영할 것

**Comment by berryv** [comment]
<img width="714" alt="2016-07-01 2 44 15" src="https://cloud.githubusercontent.com/assets/12493128/16498268/f778e2d2-3f35-11e6-8401-2b9e611c9804.png">
아.. 너무 어려워요... ㅜ ㅜ

**Comment by dalikim** [comment]
제 위로 대외협력이 지나는게 맞는지 궁금합니다. 물론 제가 대외협력 안한다는 건 아니지만,
각자 모든 분야에 조금씩 걸쳐 있는 상황을 표현하는게 의미 있을까 싶은데요.

**Comment by berryv** [comment]
<img width="605" alt="2016-07-01 4 27 31" src="https://cloud.githubusercontent.com/assets/12493128/16514771/053e6612-3fa9-11e6-8f06-90e67b4611b5.png">

**Comment by berryv** [comment]
docs 에 반영할 것
