### ISSUE TITLE
브랜드방향x콜라보레이션 프로젝트

### ISSUE THREAD

**Issue by berryv** [parti-xyz/parti-group#133]
이우철 대표님 미팅에 자료로 가져감. 
빠띠 광장 이미지도 포함.

**Comment by berryv** [comment]
추가 
-(1) 미팅때 논의한 사항과 (2) 전략 결정사항 그리고 (3) nexr step 도 컨택리포트
-바글와글시민법안 아이디어

**Comment by dalikim** [comment]
결과물은 뭔가요? @berryv

**Comment by berryv** [comment]
@dalikim  
1) 브랜드방향x콜라보레이션 프로젝트 지금까지 한 부분을 정리해가고, docs 에 정리한 것 더해서 .. 타겟은 어디에 먹혔었는지, 반응이 어땠었는지, 뭘 더 해볼지도 정리해봅니다. 
2) 지금 하는 프로젝트 외 청정넷과 마을 사업단 쪽에 같이 해볼 거리들 (빠띠메이커와 하려했던) 기획을 잡아보려 합니다. 버블도 포함됩니다.

**Comment by dalikim** [comment]
우워~ 뭔가 거대한 듯하네요. 서로 연관이 되어 있어 두 개로 쪼갤 수는 없나 보죠?

**Comment by berryv** [comment]
한겨레는 쪼개서 해야할 것 같네요. 그래도 같이 정리하기는 해야해요 ' ' a ;;
