### ISSUE TITLE
up.parti.xyz 푸터 쥐픽쳐스 -> 국범근

### ISSUE THREAD

**Issue by berryv** [parti-xyz/parti-group#135]
국범근 https://www.facebook.com/profile.php?id=100001923176001&fref=ts

**Comment by dalikim** [comment]
푸터 변경인가요? 푸터에 URL 고쳐달라는 건가요? 아님 푸터에 쥐픽쳐스라고 된 이미지를 고쳐달라는 건지요? @berry502

**Comment by dalikim** [comment]
@berry502 닫고 버블 프로젝트로 옮기겠습니다.
