### ISSUE TITLE
개별 빠띠 운영가이드 v0.9

### ISSUE THREAD

**Issue by luluv** [parti-xyz/parti-group#143]
- 빠띠 사용 전까지의 과정/ 고민 반영해보기 
- 사용안내 메시지 추가하기

**Comment by luluv** [comment]
https://docs.google.com/document/d/1GYkcCZf2H6xWXFgX3mpgVAfS8BxybXzlVU1Ta4ki8lk/edit#

**Comment by luluv** [comment]
@dalikim 1.6릴리즈에서 개별 빠띠 배너 화면 상단에 붙여주세요.

**Comment by dalikim** [comment]
@berryv 메인과는 구별되는 조금 다른 띠배너가 들어가야면 합니다. 디자인 가능할까요? (  @luluv )

**Comment by berryv** [comment]
함께 만드는 빠띠, 이렇게 참여해보세요 [운영가이드]

**Comment by luluv** [comment]
@dalikim 위에 베리님이 작성해주신 것이 개별 빠띠 운영가이드 띠배너에 들어갈 문구입니다 :)

**Comment by berryv** [comment]
![parti_guidebanner_1](https://cloud.githubusercontent.com/assets/12493128/16139106/6116768a-347f-11e6-926e-e4a1dbb4769c.png)

이 이미지가 밝으면 배경 검은색 40% 투명도로 줘도 좋을 것 같구요 

![parti_guidebanner_2](https://cloud.githubusercontent.com/assets/12493128/16139102/57b1da44-347f-11e6-9e19-bba507dbbbc0.png)

메인에 있는 것과 조금 비슷한 것도 넣어보았습니다. 

둘다 별로면 우선 브랜드 컬러 배경으로 들어가는게 좋을 것 같아요.

**Comment by luluv** [comment]
@dalikim 깃헙 위키로 옮겼습니다!  https://github.com/parti-xyz/catan-web/wiki/%EB%B9%A0%EB%9D%A0-%EC%9A%B4%EC%98%81-%EA%B0%80%EC%9D%B4%EB%93%9C

**Comment by dalikim** [comment]
@luluv 네. 근데 이 이슈는 카탄에 있었으면 좋았겠네요. ㅎ

**Comment by luluv** [comment]
그룹/카탄 개념이 없을 때 만든 테스크라서. 이제 알았으니 앞으로 구분을 정확히 할 수 있을 것 같습니다!

**Comment by dalikim** [comment]
@luluv 오늘 중에 "위키"를 활용가이드에 넣을 수 있을까요? 위키에는 간단한 위키 설명과 함께요. 그렇게 해주시면 지금  "위키란?" 버튼을 그리로 걸고 싶습니다

**Comment by luluv** [comment]
@dalikim 넵 이 이슈를 닫고, 1.x로 다시 열게요 !
