### ISSUE TITLE
아이쿱 프로젝트 기획

### ISSUE THREAD

**Issue by berryv** [parti-xyz/parti-group#167]
'비의도적 혼입치 기준도 0.9%로 잡고 그것보다 미만이면 NON-GMO 표시가 가능하게 하자'
http://up.parti.xyz/posts/569 

GMO 정보 아카이브 + 커뮤니티 만들기 / 온라인 서명 캠페인

**Comment by rest515** [comment]
1페이지 제안서를 만듭니다.
