### ISSUE TITLE
업빠띠 OX퀴즈 : 힌트 자료 업데이트

### ISSUE THREAD

**Issue by luluv** [parti-xyz/parti-group#173]
GMO완전표시법 빠띠에 자료 업데이트

**Comment by luluv** [comment]
@qus1225 OX퀴즈 스크립트 부분에 문항별로 링크를 적어두었습니다! 

https://docs.google.com/document/d/1HI0p7PCBHM69WhjcsM-n42uDtTkKRYTiYtl2GQA10Rc/edit

**Comment by berryv** [comment]
완료
