### ISSUE TITLE
better-c 인트로 문서 검토

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#4]
완료 조건

* 폴더 https://drive.google.com/drive/folders/0B0dntzcZMPLpaEhZekhQa0hQZ0U 에 있는 자료를 읽어 본다.
* 의문점이나 주요 논의 꼭지를 각자 정리한다.
* 2015년 10월 12일(월) 스탠드업 전까지 완료
* 2015년 10월 12일(월) 스탠드업 중에 추후 일정에 대한 논의 회의를 잡는다.
* 추후 일정에 대한 이슈를 깃헙에 발행한다.

**Comment by dali-kim** [comment]
@rest515 @neonatas @baupa 

better-c 인트로 문서 읽고 이야기 하고 싶은 것을 저는 위 구글문서에 댓글로 달았습니다. 시스님께서 스탠드업 중에 슬랙 #all 채널로 이야기하자고 하셨는데, 주로 구글문서 댓글로 토론하면 어떨런지요?

**Comment by dali-kim** [comment]
@rest515 @neonatas @baupa
아 그리고 다음 주 월요일까지 완료하는 것으로 하겠습니다. 별 무리 없으시지요?
완료된 후에 일정은 어떻게 잡을까요?

**Comment by rest515** [comment]
다음주 월요일에 다음 액션을 정하면 완료하는 걸로 정하죠.

**Comment by dali-kim** [comment]
완료조건 업뎃했습니다.

**Comment by dalikim** [comment]
서비스 아이데이션 이슈 발행했습니다. #12
