### ISSUE TITLE
글감 다듬고 배포하기

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/parti-group#41]
https://parti-xyz.hackpad.com/민주주의의-시작은-입장-표명-브리게이드-zqlNEyiZPAA

**Comment by mozodev** [comment]
@parti-xyz/owners 일단 완성했는데 시간되시면 한번 읽어봐주시고 의견 주시면 감사하겠습니다. 오늘 저녁에 공개하겠습니다.

**Comment by rest515** [comment]
"실제로 정당이나 국회의원도 이 서비스를 사용해서 사람들과 대화하고 있다고 하는데," 부분은 어떤 의도인지 뒤의 문장과 연결이 모호한 듯 합니다.

**Comment by mozodev** [comment]
네 뒤에 관계를 더 중요하게 생각하고 있는거 같다는 메시지였는데 수정하다가 삭제를 안 했네요.. 수정했습니다.
@parti-xyz/owners 조금 더 다듬어보다가 이따 9시쯤 공개하겠습니다.

**Comment by mozodev** [comment]
https://medium.com/@mozo/민주주의의-시작은-입장-표명-브리게이드민주주의의-시작은-입장-표명-브리게이드-c5dae989d7a4#.6rv2vzxwf

일단 공개는 했는데, 예상대로  https://medium.com/parti-xyz-developers/about 추가해주셔야 겠네요 ㅎㅎ

https://medium.com/@mozo

**Comment by rest515** [comment]
에디터로 추가하였습니다.

**Comment by mozodev** [comment]
아 어떻게 빠띠에 공개하는지 약간 헤매다가 공개했습니다.
https://medium.com/parti-xyz-developers

**Comment by rest515** [comment]
페이스북에도 공유!
