### ISSUE TITLE
React+Redux+Rails 개발 테스트

### ISSUE THREAD

**Issue by rest515** [parti-xyz/parti-group#45]
Reac와 Redux 그리고 Rails 조합을 테스트합니다. node.js를 사용할 가능성이 있습니다.

**Comment by dalikim** [comment]
node.js를 넣은 이유는 뭘까요?

**Comment by rest515** [comment]
https://medium.com/@alexfedoseev/isomorphic-react-with-rails-part-ii-614980b65aef#.7rrm3tjmw 이 예제를 따라 가 보려고 합니다.

**Comment by rest515** [comment]
시간이 많이 지나서 일단 닫습니다.
