### ISSUE TITLE
oEmbed 테스트

### ISSUE THREAD

**Issue by rest515** [parti-xyz/parti-group#46]
프로젝트에서 본문 데이터 노출시에 사용할 oEmbed 방식을 테스트합니다.

**Comment by dalikim** [comment]
https://parti-xyz.hackpad.com/oEmbed-XNzhgUrqXhQ 핵패드 페이지 열었습니다.

**Comment by rest515** [comment]
테스트해보니 잘 되네요. 에디터에 붙여보면 좋겠습니다.
