### ISSUE TITLE
부트스트랩 확장 라이브러리 조사

### ISSUE THREAD

**Issue by rest515** [parti-xyz/parti-group#48]
기본 라이브러리가 제공하는 기능을 확장하는 방법을 찾아 봅니다.

**Comment by rest515** [comment]
bootstrap-bootstarp 프로젝트를 만들고, 필요한 컴포넌트를 정리하면서 라이브러리를 붙기로 했습니다.

**Comment by berryv** [comment]
저도 알면 제안하는데 도움이 될 것 같습니다. 검색해보긴 하겠지만 우선 아시는 링크를 공유해주실 수 있을까요?
