### ISSUE TITLE
휴대폰 parti 계정 설정

### ISSUE THREAD

**Issue by dali-kim** [parti-xyz/parti-group#5]
간단하지만 시험삼아 이슈로 만들어 봅니다.

완료 조건
* 각자 폰에 parti계정을 등록한다.

**Comment by dali-kim** [comment]
저는 추가 완료했습니다.
@neonatas 님 설정하시고 완료되시면 다른 분께 넘겨주세요.

**Comment by neonatas** [comment]
완료 했습니다.

@baupa 님께 넘김

**Comment by baupa** [comment]
저도 된 듯합니다.. @jaygoon 님께 토스합니다. ^^

**Comment by jaygoon** [comment]
저도 로그인은 했습니다. 이렇게 하면 되는건가요?

**Comment by baupa** [comment]
메일은 지금 봤네요.. 수고하셨습니다. ^^

2015-10-08 20:31 GMT+09:00 jaygoon <notifications@github.com>:

**Comment by rest515** [comment]
@dali-kim 저도 완료했습니다. 달리님께 돌리겠습니다.

**Comment by dali-kim** [comment]
모두들 수고하셨습니다.
