### ISSUE TITLE
베리 컴퓨터 개발환경설정가이드 ssh설치

### ISSUE THREAD

**Issue by berryv** [parti-xyz/parti-group#56]
꺄아~

**Comment by berryv** [comment]
https://goo.gl/YW5ZeM 여기까지 하고 무반응이거나 에러났던 것은 댓글남김

**Comment by berryv** [comment]
http://sourceforge.net/projects/git-osx-installer/files/latest/download 다운로드

**Comment by berryv** [comment]
https://goo.gl/1jXC90 마구 쳤는데 전혀 모르겠네요 흠

**Comment by mozodev** [comment]
:+1: 직접 세션 진행하기 전에 같이 한번 해볼까요? ㅎㅎㅎㅎ

**Comment by dalikim** [comment]
같이 해 볼까요?

2016-01-21 0:02 GMT+09:00 berry502 notifications@github.com:

**Comment by berryv** [comment]
1/21 세션하면서 ssh 재설치, powder 설치함. 이 이슈는 닫고 sso 새로 이슈 올리겠습니다
