### ISSUE TITLE
개발 환경에 필요한 요건 초안 마련 및 일정 수립

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#6]
완료 조건
* 개발 환경 구축에 필요한 요건 마련
* 관련한 일정 수립

**Comment by dali-kim** [comment]
@baupa 

간단한 미팅 했으면 하는데요. 아젠다는 개발 환경 구축에 필요한 요건을 간략히 간추려보는 것이구요.
저는 매일 오전 중에 시간이 됩니다. @rest515 님도 참석하실래요?

**Comment by rest515** [comment]
저는 가이드를 본 후에 팔로업하겠습니다!

Peace!

2015. 10. 8. 오전 9:36 Kim youngmin <notifications@github.com> 작성:

**Comment by baupa** [comment]
내일 오전에 시간을 잡고 이야기를 나눠보면 좋겠습니다. 저의 경우 PHP-MySQL환경과 소규모 팀에서 진행했던 경험의 수준이구요,
작업 공유는 주로 구글 드라이브나 메일로 진행을 해왔습니다. 새로운 프레임웍에 대해서는 이제부터 익혀야 하는 입장이라 방향을
제시해주시면 감사하겠습니다.

2015년 10월 8일 오전 9:36, Kim youngmin <notifications@github.com>님이 작성:

**Comment by dali-kim** [comment]
@rest515 이 제안하신게 

1. 테스트서버
2. 랩 프로젝트 킥오프
3. 페어 환경

이 세 가지인데요. 저는 비슷하지만 좀 꼬아서..

* 페어 환경 가이드 수립
* 페어 환경 실제 적용하면서 랩 프로젝트 간단하게 만들기
* engine yard에 랩 프로젝트 배포 방법 구축

요까지 하면 초기 세팅은 되지 않을까 합니다.

**Comment by dalikim** [comment]
관련된 이슈 다 만들었습니다. 완료조건 충족되어 종료 합니다.

**Comment by baupa** [comment]
수고하셨습니다. 제가 맥북을 준비하려고 하고 있는 상태인데(전에는 윈도우, 리눅스에서만 작업을 해서요..) 다음 주 쯤에 구입을 해서
보내주신 가이드를 따라가보겠습니다.

2015-10-12 7:52 GMT+09:00 Kim youngmin <notifications@github.com>:
