### ISSUE TITLE
개인별 관심 라벨 만들고 사용해보기

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/parti-group#62]
여기 레이블 달려있는 것 처럼 아이디로 만들고
좋아하는 색을 하나 골라서
이슈보다가 관심있는거에 색칠해놓고 할 수 있을 때 가져갈 수도 있겠죠?

**Comment by dalikim** [comment]
제것 라벨만 깃헙 닉네임으로 모두 조정했습니다.
