### ISSUE TITLE
협업 가이드에서 컨트리뷰터 부분 삭제

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#64]
협업가이드를 좀더 현실적으로 조정했으면 합니다. 아직 컨트리뷰터가 없으므로 그 부분을 지우면 어떨까 합니다.

논의가 길어지면 카누 띄우겠습니다.

**Comment by mozodev** [comment]
네 중복되는 부분도 많고 일단 삭제하고 필요하면 카누에서 논의하면 좋겠습니다.
