### ISSUE TITLE
카누 메일 주소

### ISSUE THREAD

**Issue by berryv** [parti-xyz/parti-group#68]
http://hackfoldr.org/parti-xyz/https%253A%252F%252Fparti-xyz.hackpad.com%252F--A68zMop8ZSf 몇가지 적어뒀어요.

**Comment by dalikim** [comment]
문의 메일 주소와 발신 전용 메일 주소 두 개면 될거 같은데 어떠세요?

주신 것 중에 canoe@과  help@로 할까요?

@berry502

**Comment by mozodev** [comment]
noreply@loomio.org 루미오에서는 이런 주소로 노티 메일이 오곤 합니다. ^^;;

**Comment by dalikim** [comment]
canoe@parti.xyz을 쓰고 있습니다.
noreply@parti.xyz도 필요하면 나중에 쓰겠습니다.
