### ISSUE TITLE
CI 페이지 만들기

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/parti-group#82]
로고 형식별로 정리
소셜 및 각종 배너 이미지
파비콘

**Comment by berry502** [comment]
스크랩 
광장 : https://kr.pinterest.com/berrybak/%EA%B4%91%EC%9E%A5/
브랜드 이미지 : https://kr.pinterest.com/berrybak/brand/
UXUI : https://kr.pinterest.com/berrybak/uxui/

**Comment by qus1225** [comment]
http://parti.xyz/about 에
빠띠가 왜 빠띠인지를 설명한다.
- participation, party 에서 유래했으며,
- 서비스내에서는 이슈를 다루는 단위를 의미한다.
