### ISSUE TITLE
메일 서명 만들기

### ISSUE THREAD

**Issue by dalikim** [parti-xyz/parti-group#85]

**Comment by dalikim** [comment]
@berry502 요 이슈 좀 끌어 올렸으면 합니다만.

**Comment by berryv** [comment]
![2016-06-14 6 23 23](https://cloud.githubusercontent.com/assets/12493128/16037824/386e871e-325d-11e6-9f40-8949fe900bfa.png)

환경설정에서 이렇게 이미지 넣고 저장하면 이미지가 깨지네요; 
너무 긴건 아닌가 싶어 내일 피드백 받고 완료하겠습니다.

**Comment by dalikim** [comment]
![1](https://cloud.githubusercontent.com/assets/1650024/16067334/6318083e-32f6-11e6-82f7-075dbd2dfa45.jpg)

슬로건도 짧아졌는데, 왼쪽에 이미지를 몰면 어떨까나요?

**Comment by berryv** [comment]
넵. 
그런데 이것도 코딩이 필요한건가요? ; 이미지가 깨져서.. 궁금해서요.

**Comment by luluv** [comment]
저는 서명이 길어서 이상하다는 생각은 안듭니다~ 달리님 의견대로 왼쪽으로 몰면 어떨지 궁금합니다.

**Comment by berryv** [comment]
텍스트로만 쓴 부분 all 메일로 보내보았고 
이미지는 https://github.com/parti-xyz/parti-group/blob/gh-pages/media/mailsign.png 에 올려보았습니다.
